# Generated by Django 3.2.7 on 2021-12-07 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Name of the subject to learn', max_length=128)),
                ('slug', models.SlugField(blank=True, help_text='Unique slug', max_length=128, null=True, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Short summary of current Subject', max_length=512, null=True)),
                ('is_visible', models.BooleanField(default=False, help_text='Define if subject (with corresponding lessons) is visible to students')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('outline', models.TextField(blank=True, help_text='Lesson outline', null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.documentfile')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.imagefile')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.subject')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.videofile')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
