# Generated by Django 3.2.7 on 2021-12-07 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lessonrating_testassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.testassignment'),
        ),
        migrations.AddField(
            model_name='subject',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.testassignment'),
        ),
        migrations.CreateModel(
            name='TestAssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.testassignment')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('answer_text', models.CharField(max_length=64)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.testassignmentquestion')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
