# Generated by Django 3.2.7 on 2021-12-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('learning', '0003_auto_20211207_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.imagefile'),
        ),
    ]
