# Generated by Django 3.2.7 on 2021-12-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20211212_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testassignmentquestion',
            name='image',
        ),
    ]
