# Generated by Django 3.2.7 on 2021-12-12 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('learning', '0006_remove_testassignmentquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignmentquestion',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.imagefile'),
        ),
    ]
