# Generated by Django 3.2.7 on 2021-12-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos'),
        ),
    ]
